/**
 * Curated distress / non-distress utterance dataset
 * Based on VANI research paper: ~70 samples, label 1 = distress, 0 = non-distress
 * Includes English, Hindi (transliterated), and Marathi phrases
 */
export interface TrainingSample {
  text: string;
  label: 0 | 1;
}

export const TRAINING_DATA: TrainingSample[] = [
  // ── Distress (1) ──────────────────────────────────────────
  { text: 'help me please', label: 1 },
  { text: 'someone is following me', label: 1 },
  { text: 'bachao mujhe', label: 1 },
  { text: 'i feel unsafe right now', label: 1 },
  { text: 'help', label: 1 },
  { text: 'save me', label: 1 },
  { text: 'please help me', label: 1 },
  { text: 'emergency', label: 1 },
  { text: 'sos', label: 1 },
  { text: 'call police', label: 1 },
  { text: 'i am in danger', label: 1 },
  { text: 'someone help me', label: 1 },
  { text: 'help me now', label: 1 },
  { text: 'i am in trouble', label: 1 },
  { text: 'they are attacking me', label: 1 },
  { text: 'leave me alone', label: 1 },
  { text: 'do not touch me', label: 1 },
  { text: 'call ambulance', label: 1 },
  { text: 'i am scared', label: 1 },
  { text: 'get away from me', label: 1 },
  { text: 'bachao', label: 1 },
  { text: 'madad karo', label: 1 },
  { text: 'mujhe bachao', label: 1 },
  { text: 'koi bachao', label: 1 },
  { text: 'police bulao', label: 1 },
  { text: 'main danger mein hoon', label: 1 },
  { text: 'jaldi help karo', label: 1 },
  { text: 'chhodo mujhe', label: 1 },
  { text: 'mat chuo', label: 1 },
  { text: 'mala vachva', label: 1 },
  { text: 'madad kara', label: 1 },
  { text: 'please somebody help', label: 1 },
  { text: 'i need help right now', label: 1 },
  { text: 'there is a fire', label: 1 },
  { text: 'i am being robbed', label: 1 },
  { text: 'someone is breaking in', label: 1 },
  { text: 'i am hurt badly', label: 1 },
  { text: 'i am bleeding', label: 1 },
  { text: 'please call for help', label: 1 },
  { text: 'i cannot breathe', label: 1 },

  // ── Non-distress (0) ──────────────────────────────────────
  { text: 'what time is it', label: 0 },
  { text: 'let us go home', label: 0 },
  { text: 'open the door', label: 0 },
  { text: 'hello how are you', label: 0 },
  { text: 'good morning', label: 0 },
  { text: 'what is for dinner', label: 0 },
  { text: 'can you help me with homework', label: 0 },
  { text: 'turn off the lights', label: 0 },
  { text: 'where is the remote', label: 0 },
  { text: 'i am going to the store', label: 0 },
  { text: 'the weather is nice today', label: 0 },
  { text: 'i will be there in five minutes', label: 0 },
  { text: 'please pass the salt', label: 0 },
  { text: 'have a good day', label: 0 },
  { text: 'see you later', label: 0 },
  { text: 'i am tired', label: 0 },
  { text: 'let me check my phone', label: 0 },
  { text: 'the movie was great', label: 0 },
  { text: 'i finished my work', label: 0 },
  { text: 'do you want coffee', label: 0 },
  { text: 'kaise ho', label: 0 },
  { text: 'khana kha lo', label: 0 },
  { text: 'main ghar ja raha hoon', label: 0 },
  { text: 'chai peelo', label: 0 },
  { text: 'subah ho gayi', label: 0 },
  { text: 'what should we eat', label: 0 },
  { text: 'play some music', label: 0 },
  { text: 'it is raining outside', label: 0 },
  { text: 'i love this song', label: 0 },
  { text: 'close the window', label: 0 },
];
